#ifndef   __NOVEMBERIZING_X_DESCRIPTOR_EVENT__GENERATOR__H__
#define   __NOVEMBERIZING_X_DESCRIPTOR_EVENT__GENERATOR__H__

#include <x/event.h>

#endif // __NOVEMBERIZING_X_DESCRIPTOR_EVENT__GENERATOR__H__
