#ifndef   __NOVEMBERIZING_X_COMMAND_EVENT__SUBSCRIPTION__H__
#define   __NOVEMBERIZING_X_COMMAND_EVENT__SUBSCRIPTION__H__

#include <x/command.h>

#endif // __NOVEMBERIZING_X_COMMAND_EVENT__SUBSCRIPTION__H__
